### ISSUE TITLE
Unbound variable in test script

### ISSUE THREAD

**Issue by joshualiangxy** [nus-cs2030s-2021-s2/lab3-skeleton#1]
My student ran into an issue with the test script where variable `num_failed` is unbound:
![image](https://user-images.githubusercontent.com/28984700/107631195-90cebd80-6c9f-11eb-88de-fd73cde87e8a.png)

The issue seems to be that `num_failed` was used before initialization.

Here is the line where the error occurs:
https://github.com/nus-cs2030s-2021-s2/lab3-skeleton/blob/adad507b92781c5f93eb7c645d25986e371571f2/test.sh#L33

And here is the initialization of the `num_failed` later in the script:
https://github.com/nus-cs2030s-2021-s2/lab3-skeleton/blob/adad507b92781c5f93eb7c645d25986e371571f2/test.sh#L51

It's a simple fix by just moving the initialization up, but I'm not sure if it's possible to make this change for the students now that they have already started on the lab.

**Comment by weitsang** [comment]
:+1:  fixed
